### ISSUE TITLE
Production Mode - FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by rahmatkruniawan** [amilajack/erb-sqlite-example#4]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I have been change this in package json 

> "package-win": "npm run build && build --win --x64 --max_old_space_size=8224",

But stil got that error

**Comment by amilajack** [comment]
Interesting. Are you on macOS? What happens when you `npm run package`?

**Comment by rahmatkruniawan** [comment]
@amilajack  no, I'm on windows.
when I run `yarn package`  still got 

> [1]  90% recording
0ms recording
[1]  91% additional asset processing
[1] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by amilajack** [comment]
Hmm that's interesting. What are your node and npm versions? Also how big is your build?

**Comment by amilajack** [comment]
Also see this bug: https://github.com/chentsulin/electron-react-boilerplate/issues/1045

**Comment by rahmatkruniawan** [comment]
@amilajack  my node version is 6.9.1 and I user yarn version 0.22.0.
How big my project ? hmm I don't know to tell how big my project. 
Can you advise me how to measure my project?

**Comment by amilajack** [comment]
Sure. If you running `npm run build-renderer` and then `npm run build-main`. Webpack should output build sizes immediately after the build finishes.

**Comment by amilajack** [comment]
<img width="549" alt="screen shot 2017-06-08 at 1 03 44 pm" src="https://user-images.githubusercontent.com/6374832/26948356-f32eb968-4c4a-11e7-9186-8cfe2008d21e.png">

Here's an example of the main processes's build size

**Comment by rahmatkruniawan** [comment]
when I run `npm run build-renderer` still got some error .
and command of `npm run build-main` 
![main-des](https://user-images.githubusercontent.com/9253817/26949037-9ddff706-4cc2-11e7-8c77-b32bb601a7ea.jpg)
I think that's size not all of them, becacuse not correctly compiled

**Comment by amilajack** [comment]
Did you see chentsulin/electron-react-boilerplate#1045?

**Comment by rahmatkruniawan** [comment]
@amilajack  sry I forgot to save my edited file 
not big project, i think.
![snapshot_2017-6-9_3-27-59](https://user-images.githubusercontent.com/9253817/26949324-b7932c3a-4cc3-11e7-806d-75c2cc3b1cb7.jpg)

**Comment by amilajack** [comment]
But did you try changing to `devtool: 'eval'`? Please try that

**Comment by rahmatkruniawan** [comment]
@amilajack  sry I forgot to save it. 
Working fine for now. Thanks for help
