### ISSUE TITLE
Auto Update Apps allready build

### ISSUE THREAD

**Issue by rahmatkruniawan** [amilajack/erb-sqlite-example#6]
**This's my scenario.**
I build the installer and distribute it.
But I want the app I distribute to change if I make a change in the source code. But I do not want anyone who has installed my apps it must install again the application that I created.
So it's like auto update. Is it possible to do that with this ERB?

**Comment by rahmatkruniawan** [comment]
@amilajack  I really need help for this. 
I really need your advice

**Comment by amilajack** [comment]
Please ask this question in the gitter chat. Opening issues isnt the right way to do this.
